/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Bren
 */
public class frmMenu extends javax.swing.JFrame {

    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        opAgregar = new javax.swing.JMenuItem();
        opModificar = new javax.swing.JMenuItem();
        opEliminar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        opMasculino = new javax.swing.JMenuItem();
        opFemenino = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        opInventario = new javax.swing.JMenuItem();
        opVentas = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1091, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );

        jMenuBar1.setBackground(new java.awt.Color(153, 153, 153));
        jMenuBar1.setForeground(new java.awt.Color(0, 153, 153));
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N

        jMenu1.setBackground(new java.awt.Color(153, 153, 153));
        jMenu1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jMenu1.setForeground(new java.awt.Color(255, 153, 0));
        jMenu1.setText("ADMINISTRAR PRODUCTOS");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jMenu1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        opAgregar.setText("AGREGAR");
        opAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opAgregarActionPerformed(evt);
            }
        });
        jMenu1.add(opAgregar);

        opModificar.setText("MODIFICAR");
        opModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opModificarActionPerformed(evt);
            }
        });
        jMenu1.add(opModificar);

        opEliminar.setText("ELIMINAR");
        opEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opEliminarActionPerformed(evt);
            }
        });
        jMenu1.add(opEliminar);

        jMenuBar1.add(jMenu1);

        jMenu2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jMenu2.setForeground(new java.awt.Color(255, 153, 0));
        jMenu2.setText("ADMINISTRAR EMPLEADOS");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        opMasculino.setText("MASCULINO");
        opMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opMasculinoActionPerformed(evt);
            }
        });
        jMenu2.add(opMasculino);

        opFemenino.setText("FEMENINO");
        opFemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opFemeninoActionPerformed(evt);
            }
        });
        jMenu2.add(opFemenino);

        jMenuBar1.add(jMenu2);

        jMenu3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153)));
        jMenu3.setForeground(new java.awt.Color(255, 153, 0));
        jMenu3.setText("VISUALIZAR");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        opInventario.setText("INVENTARIO");
        opInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opInventarioActionPerformed(evt);
            }
        });
        jMenu3.add(opInventario);

        opVentas.setText("VENTAS");
        opVentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opVentasActionPerformed(evt);
            }
        });
        jMenu3.add(opVentas);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void opModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opModificarActionPerformed
        // TODO add your handling code here:
        frmModificar producto = new frmModificar();
        escritorio.add(producto);
        producto.show();
    }//GEN-LAST:event_opModificarActionPerformed

    private void opMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opMasculinoActionPerformed
        // TODO add your handling code here:
        frmMasculino personal = new frmMasculino();
        escritorio.add(personal);
        personal.show();
    }//GEN-LAST:event_opMasculinoActionPerformed

    private void opAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opAgregarActionPerformed
        // TODO add your handling code here:
        frmAgregar producto = new frmAgregar();
        escritorio.add(producto);
        producto.show();
    }//GEN-LAST:event_opAgregarActionPerformed

    private void opEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opEliminarActionPerformed
        // TODO add your handling code here:
        frmEliminar producto = new frmEliminar();
        escritorio.add(producto);
        producto.show();
    }//GEN-LAST:event_opEliminarActionPerformed

    private void opFemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opFemeninoActionPerformed
        // TODO add your handling code here:
        frmFemenino personal = new frmFemenino();
        escritorio.add(personal);
        personal.show();
    }//GEN-LAST:event_opFemeninoActionPerformed

    private void opInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opInventarioActionPerformed
        // TODO add your handling code here:
        frmInventario visualizar = new frmInventario();
        escritorio.add(visualizar);
        visualizar.show();
    }//GEN-LAST:event_opInventarioActionPerformed

    private void opVentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opVentasActionPerformed
        // TODO add your handling code here:
        frmVentas visualizar = new frmVentas();
        escritorio.add(visualizar);
        visualizar.show();
    }//GEN-LAST:event_opVentasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem opAgregar;
    private javax.swing.JMenuItem opEliminar;
    private javax.swing.JMenuItem opFemenino;
    private javax.swing.JMenuItem opInventario;
    private javax.swing.JMenuItem opMasculino;
    private javax.swing.JMenuItem opModificar;
    private javax.swing.JMenuItem opVentas;
    // End of variables declaration//GEN-END:variables
}
